Checkpoint: two instances running using an instance template

diff --git a/templates/main.yml b/templates/main.yml
--- a/templates/main.yml
+++ b/templates/main.yml
@@ -46,6 +46,14 @@ Resources:
           Action: sts:AssumeRole
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/CloudWatchFullAccess
+      Policies:
+        - PolicyName: ec2DescribeTags
+          PolicyDocument:
+            Version: 2012-10-17
+            Statement:
+              - Effect: Allow
+                Action: 'ec2:DescribeTags'
+                Resource: '*'
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
@@ -56,75 +64,121 @@ Resources:
       Roles:
         - Ref: InstanceRole
 
-  Instance:
-    Type: AWS::EC2::Instance
-    # Wait for signal before marking the new instance as created (see Userdata script)
-    CreationPolicy:
-      ResourceSignal:
-        Timeout: PT5M
-        Count: 1
+  InstanceLaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
     Metadata:
       AWS::CloudFormation::Init:
         config:
           packages:
             yum:
+              ruby: []
               wget: []
               unzip: []
+              jq: []
     Properties:
-      ImageId: !Ref EC2AMI
-      KeyName: !Ref KeyName
-      InstanceType: !Ref EC2InstanceType
-      IamInstanceProfile: !Ref InstanceProfile
-      Monitoring: true
-      SecurityGroupIds:
-        - !GetAtt SecurityGroup.GroupId
+      LaunchTemplateName: !Sub 'LaunchTemplate_${AWS::StackName}'
+      LaunchTemplateData:
+        ImageId: !Ref EC2AMI
+        KeyName: !Ref KeyName
+        InstanceType: !Ref EC2InstanceType
+        IamInstanceProfile:
+          Arn: !GetAtt InstanceProfile.Arn
+        Monitoring:
+          Enabled: true
+        SecurityGroupIds:
+          - !GetAtt SecurityGroup.GroupId
+        UserData:
+          Fn::Base64: !Sub |
+            #!/bin/bash -xe
+
+            # send script output to /tmp so we can debug boot failures
+            exec > /tmp/userdata.log 2>&1
+
+            # Update all packages
+            yum -y update
+
+            # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
+            yum install -y aws-cfn-bootstrap
+
+            cat > /tmp/install_script.sh << EOF
+              # Install deps
+              cd /usr/local 
+              sudo wget https://go.dev/dl/go1.17.8.linux-amd64.tar.gz
+              sudo tar -xzf go1.17.8.linux-amd64.tar.gz
+              sudo rm -f go1.17.8.linux-amd64.tar.gz
+              cd /etc/profile.d
+              echo 'export PATH=\$PATH:/usr/local/go/bin' > /tmp/go.sh
+              echo 'export GOPATH=\$HOME/go' >> /tmp/go.sh
+              sudo mv /tmp/go.sh .
+              sudo chown root:root ./go.sh
+
+              # Dot source the files to ensure that variables are available within the current shell
+              . /home/ec2-user/.bashrc
+              . /etc/profile.d/go.sh
+            EOF
+
+            chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+            sleep 1; su - ec2-user -c "/tmp/install_script.sh"
+
+            # Have CloudFormation install any files and packages from the metadata
+            /opt/aws/bin/cfn-init -v \
+              --stack ${AWS::StackName} \
+              --region ${AWS::Region} \
+              --resource InstanceLaunchTemplate
+
+            # Query the EC2 metadata service for this instance's instance-id
+            export INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
+
+            # Query EC2 describeTags method and pull our the CFN Logical ID for this instance
+            export LOGICAL_ID=`aws \
+              --region ${AWS::Region} ec2 describe-tags \
+               --filters "Name=resource-id,Values=${!INSTANCE_ID}" \
+                        "Name=key,Values=aws:cloudformation:logical-id" \
+               | jq -r ".Tags[0].Value"`
+
+            # Signal to CloudFormation that the instance is ready
+            /opt/aws/bin/cfn-signal -e $? \
+              --stack ${AWS::StackName} \
+              --region ${AWS::Region} \
+              --resource ${!LOGICAL_ID}
+
+  Instance:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT5M
+        Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
-      UserData:
-        Fn::Base64: !Sub |
-          #!/bin/bash -xe
-          # send script output to /tmp so we can debug boot failures
-          exec > /tmp/userdata.log 2>&1
 
-          # Update all packages
-          yum -y update
-
-          # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
-          yum install -y aws-cfn-bootstrap
-
-          # Have CloudFormation install any files and packages from the metadata
-          /opt/aws/bin/cfn-init -v \
-            --stack ${AWS::StackName} \
-            --region ${AWS::Region} \
-            --resource Instance
-
-          cat > /tmp/install_script.sh << EOF
-            # Install deps
-            cd /usr/local 
-            sudo wget https://go.dev/dl/go1.17.8.linux-amd64.tar.gz
-            sudo tar -xzf go1.17.8.linux-amd64.tar.gz 
-            sudo rm -f go1.17.8.linux-amd64.tar.gz  
-            cd /etc/profile.d
-            echo 'export PATH=\$PATH:/usr/local/go/bin' > /tmp/go.sh
-            echo 'export GOPATH=\$HOME/go' >> /tmp/go.sh
-            sudo mv /tmp/go.sh .
-            sudo chown root:root ./go.sh
-
-            # Dot source the files to ensure that variables are available within the current shell
-            . /home/ec2-user/.bashrc
-            . /etc/profile.d/go.sh
-          EOF
-
-          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
-          sleep 1; su - ec2-user -c "/tmp/install_script.sh"
-
-          # Signal to CloudFormation that the instance is ready
-          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+  Instance2:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT5M
+        Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
 
 Outputs:
-  InstanceDNS:
+  InstanceEndpoint:
     Description: The DNS name for the created instance
     Value: !Sub 'http://${Instance.PublicDnsName}:8080'
     Export:
-      Name: InstanceDNS
+      Name: InstanceEndpoint
+
+  InstanceEndpoint2:
+    Description: The DNS name for the created instance
+    Value: !Sub 'http://${Instance2.PublicDnsName}:8080'
+    Export:
+      Name: InstanceEndpoint2
